server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/apisix
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  jackson:
    serialization:
      indent-output: true
