# apisix/config.yaml
apisix:
  # 單埠監聽 HTTP 請求
  node_listen:
    - 9080
  # 禁用 Admin API（Standalone 模式下不可開啟）
  enable_admin: false

deployment:
  # 啟用 Standalone 模式
  role: data_plane
  role_data_plane:
    config_provider: yaml