version: "3"

services:
  etcd:
    container_name: etcd
    image: bitnami/etcd:3.5.17
    volumes:
      - ./etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    healthcheck:
      test: "etcdctl endpoint health"
      interval: 5s
      timeout: 30s
      retries: 5
    ports:
      - "2379:2379"
    networks:
      apisix:

  apisix:
    container_name: apisix
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    volumes:
      - ./apisix_conf/conf.yaml:/usr/local/apisix/conf/config.yaml:ro
    restart: always
    depends_on:
      etcd:
        condition: service_healthy
    ports:
      - "9190:9190/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local