spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/apisix
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

apisix:
  admin:
    base-url: "http://localhost:9091/apisix/admin"
    api-key: "edd1c9f034335f136f87ad84b625c8f1"
